In [1]:
import numpy as np

In [2]:
a=[[1,2], [3,4], [5,6]]
A=np.array(a)
B=np.add(A,10)

print("A = " + str(A))
print("B = " + str(B))


A = [[1 2]
 [3 4]
 [5 6]]
B = [[11 12]
 [13 14]
 [15 16]]


In [9]:
fit = [1, 2, 3, 4]
ploty = np.add(fit, 10)

vsFP = np.vstack([fit, ploty])
print("np.vstack((fit, ploty) = "+ str(vsFP))
print("shape(np.vstack(fit, ploty)) = "+ str(vsFP.shape))
print("np.vstack(fit, ploty).T = "+ str(vsFP.T))


np.vstack((fit, ploty) = [[ 1  2  3  4]
 [11 12 13 14]]
shape(np.vstack(fit, ploty)) = (2, 4)
np.vstack(fit, ploty).T = [[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]]


In [4]:
print("hstack(A,B) => " + str(np.hstack((A,B))))
print("vstack(A,B) => " + str(np.vstack((A,B))))
print("dstack(A,B) => " + str(np.dstack((A,B))))

hstack(A,B) => [[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]]
vstack(A,B) => [[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 12]
 [13 14]
 [15 16]]
dstack(A,B) => [[[ 1 11]
  [ 2 12]]

 [[ 3 13]
  [ 4 14]]

 [[ 5 15]
  [ 6 16]]]


In [10]:
C = np.array([1,2,3,4,5,6])
D = np.add(C,10)

In [14]:
ret = np.transpose(np.vstack((C,D)).reshape((-1,1,2))
print("ret = " + str(ret))
print("ret.shape =" + str(ret.shape))

ret = [[[ 1  3  5 11 13 15]]

 [[ 2  4  6 12 14 16]]]
ret.shape =(2, 1, 6)
